### ISSUE TITLE
Compare master branch and gh-pages

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-markdown#11]
@tomalec the master branch and gh-pages have diverged.

What is more, the commits https://github.com/Juicy/juicy-markdown/commit/0bb5ca92d7b414520e18abdc7ada9a524ec8ddfa and https://github.com/Juicy/juicy-markdown/commit/0bb5ca92d7b414520e18abdc7ada9a524ec8ddfa are kind of similar, so I would not like to do a dumb merge. 

Could you please review this and sync the branches?

**Comment by tomalec** [comment]
Done at https://github.com/Juicy/juicy-markdown/commit/59bd5f5d63b695f34c1da9d0ee11193dab89032a
