### ISSUE TITLE
Question: Update for Polymer 1.0 in the plans?

### ISSUE THREAD

**Issue by caraya** [Juicy/juicy-markdown#5]
Are there any plans to update the component to work with Polymer 1.0?

**Comment by tomalec** [comment]
Hi, thanks for feedback!

We definitely plan to migrate all `juicy-` components to Polymer 1.0, there is two of us currently working on that, but unfortunately, we cannot give any dates, yet.

**Comment by caraya** [comment]
Thanks for the update. Let me know if I can help with testing when you're close to release
